task_templates = [
    {"title": "Move Couch",           "reward": 50, "desc": "Need help moving a couch to the second floor."},
    {"title": "Grocery Run",          "reward": 25, "desc": "Pick up groceries from Whole Foods."},
    {"title": "Dog Walking",          "reward": 20, "desc": "Walk my golden retriever for 30 mins."},
    {"title": "Assemble Furniture",   "reward": 40, "desc": "Assemble an IKEA desk."},
    {"title": "Yard Work",            "reward": 35, "desc": "Rake leaves in the backyard."},
    {"title": "Tech Support",         "reward": 30, "desc": "Help setting up a new printer."},
    {"title": "Cat Sitting",          "reward": 45, "desc": "Feed my cat while I'm away for the weekend."},
    {"title": "Car Wash",             "reward": 20, "desc": "Wash my sedan in the driveway."},
    {"title": "Tutoring",             "reward": 40, "desc": "Algebra tutoring for 8th grader."},
    {"title": "Lift Heavy Boxes",     "reward": 15, "desc": "Help move 5 boxes to the garage."},
    {"title": "Move Dining Table",    "reward": 45, "desc": "Help relocate a dining table to a new apartment."},
    {"title": "Pharmacy Pickup",      "reward": 15, "desc": "Pick up a prescription from CVS."},
    {"title": "Walk Two Huskies",     "reward": 30, "desc": "Walk two huskies around the park for 45 mins."},
    {"title": "Mount TV",             "reward": 35, "desc": "Mount a 55-inch TV on a living room wall."},
    {"title": "Garden Weeding",       "reward": 25, "desc": "Weed the front garden beds and trim hedges."},
    {"title": "WiFi Setup",           "reward": 25, "desc": "Set up a new mesh WiFi system at home."},
    {"title": "Pet Sitting",          "reward": 40, "desc": "Watch my two dogs overnight while I travel."},
    {"title": "Bike Repair",          "reward": 20, "desc": "Fix a flat tire and adjust brakes on my bike."},
    {"title": "Math Tutoring",        "reward": 35, "desc": "Help with calculus homework for a college student."},
    {"title": "Garage Cleanup",       "reward": 30, "desc": "Help organize and clean out a cluttered garage."},
    {"title": "Errands - Urgent", "reward": 21, "desc": "Grocery shopping for a large home."},
    {"title": "Auto Care - Afternoon", "reward": 23, "desc": "Detailing for a nearby home."},
    {"title": "Gardening - Urgent", "reward": 45, "desc": "Plant flowers for a nearby home."},
    {"title": "Gardening - Afternoon", "reward": 31, "desc": "Trim hedges for a large home."},
    {"title": "Tutoring - Afternoon", "reward": 39, "desc": "Science homework help for a small home."},
    {"title": "Gardening - Urgent", "reward": 28, "desc": "Trim hedges for a small home."},
    {"title": "Tech Support - Urgent", "reward": 55, "desc": "Computer troubleshooting for a small home."},
    {"title": "Moving Help - Afternoon", "reward": 43, "desc": "Help move boxes for a small home."},
    {"title": "Tutoring - Urgent", "reward": 50, "desc": "Science homework help for a small home."},
    {"title": "Moving Help - Urgent", "reward": 45, "desc": "Relocate furniture for a nearby home."},
    {"title": "Errands - Weekend", "reward": 34, "desc": "Pick up dry cleaning for a nearby home."},
    {"title": "Assembly - Afternoon", "reward": 41, "desc": "Mount TV for a small home."},
    {"title": "Assembly - Urgent", "reward": 38, "desc": "Mount TV for a nearby home."},
    {"title": "Tutoring - Urgent", "reward": 26, "desc": "Math tutoring for a large home."},
    {"title": "Moving Help - Weekend", "reward": 45, "desc": "Unload truck for a small home."},
    {"title": "Tech Support - Quick", "reward": 57, "desc": "Fix printer for a large home."},
    {"title": "Tech Support - Urgent", "reward": 57, "desc": "Computer troubleshooting for a nearby home."},
    {"title": "Gardening - Quick", "reward": 47, "desc": "Mow lawn for a large home."},
    {"title": "Cleaning - Weekend", "reward": 51, "desc": "Deep clean apartment for a small home."},
    {"title": "Tutoring - Afternoon", "reward": 31, "desc": "Math tutoring for a nearby home."},
    {"title": "Tech Support - Weekend", "reward": 64, "desc": "Computer troubleshooting for a small home."},
    {"title": "Cleaning - Afternoon", "reward": 49, "desc": "Window washing for a small home."},
    {"title": "Cleaning - Weekend", "reward": 59, "desc": "Window washing for a small home."},
    {"title": "Event Help - Afternoon", "reward": 32, "desc": "Bartending for a nearby home."},
    {"title": "Pet Care - Quick", "reward": 26, "desc": "Cat sitting for a small home."},
    {"title": "Event Help - Afternoon", "reward": 47, "desc": "Party setup for a large home."},
    {"title": "Event Help - Quick", "reward": 52, "desc": "Bartending for a nearby home."},
    {"title": "Event Help - Quick", "reward": 43, "desc": "Party setup for a small home."},
    {"title": "Assembly - Weekend", "reward": 37, "desc": "IKEA furniture assembly for a large home."},
    {"title": "Pet Care - Afternoon", "reward": 38, "desc": "Dog walking for a large home."},
    {"title": "Auto Care - Urgent", "reward": 26, "desc": "Car wash for a nearby home."},
    {"title": "Auto Care - Afternoon", "reward": 28, "desc": "Detailing for a nearby home."},
    {"title": "Gardening - Afternoon", "reward": 46, "desc": "Trim hedges for a nearby home."},
    {"title": "Auto Care - Urgent", "reward": 44, "desc": "Car wash for a small home."},
    {"title": "Cleaning - Quick", "reward": 41, "desc": "Window washing for a large home."},
    {"title": "Moving Help - Weekend", "reward": 52, "desc": "Relocate furniture for a large home."},
    {"title": "Errands - Weekend", "reward": 23, "desc": "Pick up dry cleaning for a nearby home."},
    {"title": "Pet Care - Afternoon", "reward": 28, "desc": "Cat sitting for a nearby home."},
    {"title": "Event Help - Afternoon", "reward": 39, "desc": "Party setup for a large home."},
    {"title": "Moving Help - Urgent", "reward": 49, "desc": "Unload truck for a large home."},
    {"title": "Event Help - Weekend", "reward": 49, "desc": "Bartending for a large home."},
    {"title": "Tutoring - Afternoon", "reward": 36, "desc": "Math tutoring for a small home."},
    {"title": "Auto Care - Urgent", "reward": 23, "desc": "Detailing for a nearby home."},
    {"title": "Tech Support - Weekend", "reward": 45, "desc": "Fix printer for a small home."},
    {"title": "Moving Help - Weekend", "reward": 70, "desc": "Help move boxes for a small home."},
    {"title": "Tech Support - Quick", "reward": 40, "desc": "Setup WiFi for a small home."},
    {"title": "Assembly - Afternoon", "reward": 35, "desc": "Mount TV for a large home."},
    {"title": "Moving Help - Urgent", "reward": 77, "desc": "Relocate furniture for a small home."},
    {"title": "Event Help - Weekend", "reward": 31, "desc": "Waitstaff for a large home."},
    {"title": "Cleaning - Weekend", "reward": 31, "desc": "Window washing for a nearby home."},
]
